### ISSUE TITLE
Dynamic scope

### ISSUE THREAD

**Issue by aac** [lancejpollard/authlogic-connect#13]
Hi Lance,

What's the best way to support dynamically setting the scope (in particular, for Facebook)?  Right now it's handled by the settings config, correct?

Thanks,
Andrew

**Comment by lancejpollard** [comment]
I just pushed this line:

```
@consumer = OAuth2::Client.new(credentials[:key], credentials[:secret], config.merge(credentials[:options] || {}))
```

That way you can define an `:options` key in your `config/authlogic.yml` with special tags that override default settings.

Let me know if that works, haven't used it yet.

**Comment by aac** [comment]
I can test that, but I'm actually looking for even more dynamic.  My users will be able to choose which extended permissions to give to my app individually.  So, the scope could be different for every user.  And they'll be able to add additional permissions later on.

I can do this outside of AuthlogicConnect, just interacting with Facebook directly (which is how I'm doing it now), if you think that's better handled outside of user creation/authentication.

**Comment by lancejpollard** [comment]
I am hoping this library will stand as a simple interface to oauth in general, so it should be able to do what you're describing.  If you make it more dynamic, I will definitely include them in the project if you submit a pull request.  Let me know :)

**Comment by aac** [comment]
I haven't done any plug-in development yet, but I'm happy to look at it.  Any thoughts on these aspects:
- Should scope be a column (or columns) in the record?  That way it can be treated just like other params from the form.  Or should it only exist long enough to make the request, and then forgotten (aka, not stored locally)?
- What happens if the user removes permissions from Facebook?  Then our local record (if we kept one) would be out of sync?  

In my project right now, I marshall a hash into a text column in the record, where key and value are the facebook extended permission and true/false.  I'm mainly doing it this way so that I can add any new permissions (if I add a new feature that needs other data, or if FB adds new access) without changing the schema.

**Comment by lancejpollard** [comment]
I wouldn't add scope as a column to any of the existing models.  I'd create a new table with a foreign key, unless it's going to be very dynamic, maybe add a text/hash column to the token, `data`.

I have to handle the second point.  On the list :).

**Comment by aac** [comment]
I just tried out your first change for dynamic scope, but it doesn't seem to be working.

I added this to the authlogic.yml:
    options: 
      scope: "offline_access, user_birthday"

And in OAuth::consumer, where the merge occurs, that scope is merged correctly and makes it into the consumer.

It looks like 

```
return consumer.web_server.authorize_url(options)
```

in OAuthToken::authorize_url, the options params (which come from token_class.config, which is a FacebookToken class from facebook_token.rb) are used instead of the consumer's options.  I'll try to figure out what the fix is.

**Comment by aac** [comment]
Just sent you a patch via email.

**Comment by lancejpollard** [comment]
thanks, will take a look at it soon.

**Comment by lancejpollard** [comment]
looks good, integrated, will push hopefully tonight.
