### ISSUE TITLE
post requests

### ISSUE THREAD

**Issue by aac** [lancejpollard/authlogic-connect#14]
I can't seem to find native support for making post requests to the API.  Am I just looking in the wrong place, or is this coming in the future?  (I'll try to add it in in the meantime . . . )

Thanks!

**Comment by lancejpollard** [comment]
Should be added at some point, you can try setting `:http_method => "post"` in the `settings` hash, but you might run into "Invalid Signature" errors from the oauth provider.  Will look into that.

**Comment by aac** [comment]
This works too, after fixing the ID10T problem I had with the other issue.  I've been making the call (the twitter token).client.post(...).  Is it worth just adding a post function in oauth_token.rb that wraps client.post in the same way that the get function does?

**Comment by lancejpollard** [comment]
yeah, that would be real nice.  If you get it before me let me know!  I'm going to start working on this this weekend.

**Comment by aac** [comment]
I've got it, lemme see if I can figure out the pull request ;)

**Comment by lancejpollard** [comment]
I'll get to it as fast as I can, real busy at the moment :)  I got your pull requests, thanks!  I see you're going to the Heroku thing in SF, see you there!

**Comment by aac** [comment]
Indeed, should be an interesting gathering.  That'll actually be my first rails/web-dev event.

**Comment by aac** [comment]
And on the topic of Heroku, any idea how I can get my local changes to -connect up there for use?  Do I need to put the source for the gem in my own repo?

**Comment by lancejpollard** [comment]
do you have any other changes you'd like me to integrate, just merged with your branch, will publish to rubygems if not :).  Thanks a lot!

**Comment by aac** [comment]
nope, those are the ones I need.  Thanks!  I'm happy to help, this gem meets a lot of the needs of my project.

**Comment by lancejpollard** [comment]
cool, 0.0.4.06 published.
