### ISSUE TITLE
Rails 3 beta4 compatibility issue: symbolize_keys! no longer present for HashWithIndifferentAccess

### ISSUE THREAD

**Issue by ciparis** [lancejpollard/authlogic-connect#17]
After installing the rails 3 example project, trying to run it generated a 500 error pointing back to authlogic-connect:

<code>
NoMethodError (undefined method `symbolize_keys!' for #<ActiveSupport::HashWithIndifferentAccess:0x000001016818a0>):
/Users/blah/.bundle/ruby/1.9.1/gems/authlogic-connect-0.0.4.05/lib/authlogic_connect/common/variables.rb:16:in`auth_params'
</code>

I've tried both 4.05 and 4.06 -- same results. I'm not familiar enough with what is being done here to troubleshoot it effectivel, but I do see notes in the rails 3 changelog that this method was removed as part of beta 3. Is there a simple fix?

**Comment by ciparis** [comment]
Commenting this line out seemed to work (for Twitter anyway).

**Comment by lancejpollard** [comment]
fixed
