### ISSUE TITLE
Consumer is corrupted if oauth and api paths are different

### ISSUE THREAD

**Issue by aac** [lancejpollard/authlogic-connect#18]
Hey Lance,

I thought my reset_consumer fix would be sufficient for this . . . but it only works in the happy land of a single user/single access test environment.  As soon as _any_ user authorizes (in particular, with Foursquare), that network's OauthToken's consumer will be corrupted, so any future API calls will be directed to the wrong address.  It works in the single user/access case simply because there aren't API calls being made concurrently to the auth process.

Any thoughts on the best way to fix this?  Is there anything wrong with just building a new consumer every time instead of caching it?  (or maybe, every time for auth . . . and only caching for API or something?)

-Andrew

**Comment by aac** [comment]
So, not caching the consumer does seem to be _a_ fix.

**Comment by lancejpollard** [comment]
Did I really make that a class method :p.  Good catch, I'll change this right away.

**Comment by lancejpollard** [comment]
fixed
