### ISSUE TITLE
Example Facebook Stream publish?

### ISSUE THREAD

**Issue by ciparis** [lancejpollard/authlogic-connect#30]
I'm not sure what a Facebook stream publish would look like. Something along the lines of:
    def facebook
      if token = authenticated_with?(:facebook)
        @facebook ||= JSON.parse(token.post("/me/feed", {:message => "test"}))
        puts "FACEBOOK LOG: "+@facebook.inspect
      end
    end

...but this just returns a 500 error from Facebook. Am I close?

(side note: the permissions requested might be better off someplace besides inside the gem)

**Comment by lancejpollard** [comment]
yeah that looks good to me, let me try it out over here.

**Comment by ciparis** [comment]
Thanks -- theres a Paypal tip with your name on it if I can get this working :)

**Comment by lancejpollard** [comment]
Great!

You just need to specify the scope when Facebook creates the access token (when the user grants Facebook permission).

[http://developers.facebook.com/docs/authentication/permissions](http://developers.facebook.com/docs/authentication/permissions)

Place this in the config.yml file:

```
connect:
  facebook:
    key: "app-key"
    secret: "secret"
    options:
      scope: "email, offline_access, publish_stream"
```

Then this works:

```
def post
  @user = @current_user
  if token = @user.authenticated_with?(:facebook)
    begin
      @facebook = JSON.parse(token.post("https://graph.facebook.com/me/feed", {"message" => "test"}))
    rescue Exception => e
      raise JSON.parse(e.response.body)["error"]["message"]
    end
  end
end
```

![Posted to Facebook with Authlogic Connect](http://i.imgur.com/BKWQF.png)

You can revoke access to the app here:

[http://www.facebook.com/editapps.php?ref=mb](http://www.facebook.com/editapps.php?ref=mb)

Hope that helps!

Lance

**Comment by ciparis** [comment]
fabulous :) got an email address for paypal?

**Comment by macboyrules** [comment]
Yeah, I was looking into a similar thing, except I want to display the Facebook Stream.  I tried :fstream => facebook["feed"] in @profile, but that returned nil.

**Comment by lancejpollard** [comment]
Nice, glad it worked.  I setup Pledgie on the home page, does that work (same email as my profile)?  Thanks!

http://github.com/viatropos/authlogic-connect

Cheers,
Lance

**Comment by ciparis** [comment]
yep, pledged -- thank you!

**Comment by lancejpollard** [comment]
thanks man, you rock.
