### ISSUE TITLE
looks good -- how does this compare with using omniauth?

### ISSUE THREAD

**Issue by angelacode** [lancejpollard/authlogic-connect#48]
Hi, this looks great, have yet to try it but wanted to know how this was similiar/different from using omniauth?  thanks!

**Comment by lancejpollard** [comment]
Hey!  This does most of what omniauth does, but it also handles storing the info in the database; omniauth is more generic.  Personally however, I would go with omniauth.  It's entirely rack based, it's much more abstract/frameworked, and I'm sure someone will come out with an activerecord wrapper for it soon.  Use omniauth :)

Cheers
