### ISSUE TITLE
OAuth broken with latest rails security release (3.0.4) 

### ISSUE THREAD

**Issue by tekin** [lancejpollard/authlogic-connect#51]
I've not had a chance to have a proper look, but it would appear that OAuth authentication breaks with the latest security release of rails (3.0.4).

If I get the chance, I'll try and uncover why, but thought I'd post here now in case anyone else experiences this in the meantime.

**Comment by mromulus** [comment]
I can confirm this happening also, working with 3.0.3 and broken with 3.0.4.

Probably has to do with additional security needed for form submits

**Comment by tekin** [comment]
Yeah, that seems to be the case. I'm not sure why this would happen though as the CSRF protection should not kick in on a GET request. And besides, the final OAuth step shouldn't rely on the session anyway, right?

**Comment by tekin** [comment]
Ooops, I've closed this by mistake, is there a way to re-open it?

**Comment by TRMW** [comment]
I can confirm that this is also broken with 3.0.9, unless you comment out protect_from_forgery in ApplicationController.
