### ISSUE TITLE
skip password and email validations

### ISSUE THREAD

**Issue by justinvj15** [lancejpollard/authlogic-connect#54]
I am using authlogic for normal user signup,login and also authlogic connect for facebook and twitter signup,login.I need to skip password and email validation when the user signup using facebook and twitter. How should i implement it? Please help?
# user model

acts_as_authentic do |c|  
    if Proc.new{|user|user.oauth_user}  
      c.validate_email_field = false
      c.validate_password_field = false  
    end
  end

  def oauth_user
    !(self.authenticated_with?(:facebook) || self.authenticated_with?(:twitter)).nil?
  end

**Comment by kimptoc** [comment]
Hi,

Dumb question, but doesnt what you have work?

I currently just always turn off the validate options - but that is a broken solution :(

Thanks,
Chris

**Comment by justinvj15** [comment]
acts_as_authentic do |c|
    c.merge_validates_format_of_email_field_options :unless => :secondary_signup?
    c.merge_validates_length_of_email_field_options :unless => :secondary_signup?
    c.merge_validates_confirmation_of_password_field_options :unless => :secondary_signup?
    c.merge_validates_length_of_password_field_options :unless => :secondary_signup?
    c.merge_validates_length_of_password_confirmation_field_options :unless => :secondary_signup?
  end
This works for me.Secondary_signup? method returns true if it is twitter or facebook signup.
Thanks.
