### ISSUE TITLE
Connecting with twitter if a user is already signed-in using Facebook

### ISSUE THREAD

**Issue by naveedtariq** [lancejpollard/authlogic-connect#56]
Hi

Using Rails 3.0.9 and Ruby 1.9.2p290.

I am using authlogic for simple user authentication. And I need to connect to facebook and twitter to get the profile info and facebook feed and twitter tweets. There is no way defined in read me or Rails 3 example that how would i accomplish this? If you can help in this regard that would really help me and probably other users.

The problem I am currently having is. I signed-in using Facebook. authentication_type was set to "session". It creates a user in the db with all empty fields and associates an access token to it. I use the same user to take information from facebook and update it. Now i want to connect to twitter to get the tweets, when i try to authenticate through the normal procedure by passing authentication_type as "session" it creates a new user, but i just want to connect a twitter account with currently signed-in user.

Really looking forward for responses

Regards

**Comment by lancejpollard** [comment]
Hey,

I am not going to be supporting this gem anymore, I suggest switching to [Omniauth](https://github.com/intridea/omniauth).  I think it will solve your issue quickly.

Here's an example with Authlogic:  [http://github.com/madhums/omniauth-authlogic-demo](https://github.com/madhums/omniauth-authlogic-demo/blob/master/app/controllers/authorizations_controller.rb)

Best,
Lance

**Comment by divineslight** [comment]
Any plans on mentioning it somewhere on README.md viatropos? that, you are no longer supporting this gem.

Thanks.
